### ISSUE TITLE
Implement responses/activity comments

### ISSUE THREAD

**Issue by rafaelklaessen** [WELTEN/dojo-ibl-mobile#10]

**Comment by rafaelklaessen** [comment]
*Please note:* for the sake of not requesting a billion comments/responses at once from the server, we'll have to implement lazyload.

**Comment by Titogelo** [comment]
The implementation of the lazy load has been done neatly. I would add a small indicator for the users to let them know that more responses/activity comments are being loaded.

https://facebook.github.io/react-native/docs/activityindicator.html  

The logic behind should be based on the resumptionToken. If rToken => more messages will be loaded so the indicator is needed. If no rToken => no more messages to load and no indicator.

**Comment by rafaelklaessen** [comment]
I'll make the loadComments method show an indicator & hide it when the request's done.
