### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by rafaelklaessen** [WELTEN/dojo-ibl-mobile#12]
The design of the app right now isn't really serious as it's mainly for being able to implement the functionalities & UX.
After the development is 'done' (which I mean by, the functionalities & UX should be implemented), we should start looking at new design ideas.

**Comment by rafaelklaessen** [comment]
We could take inspiration from Asana (note: inspiration != copying).

**Comment by Titogelo** [comment]
that's a good note :)
