### ISSUE TITLE
Implement comment form

### ISSUE THREAD

**Issue by rafaelklaessen** [WELTEN/dojo-ibl-mobile#13]
To enable the user to actually respond to activities.

**Comment by Titogelo** [comment]
Is it possible to fix the input form at the bottom of the screen? 

Maybe for the redesign phase.

**Comment by rafaelklaessen** [comment]
I put it there purposely. But it can be moved everywhere haha

**Comment by rafaelklaessen** [comment]
But I do think this is a design issue, see #12

**Comment by Titogelo** [comment]
Yes, we can postpone it for the design phase. But now I am curious, explain your purpose ;). Back it up!

**Comment by rafaelklaessen** [comment]
Well I meant that I didn't put it there accidentally. Didn't really think it through either. 
I did it because the latest comments come last, so if the comment form would be at the top, you wouldn't see your  newly created comment.

**Comment by Titogelo** [comment]
Alright. I understand your point and make sense... but then we have two issues. One it's a design issue and the other is more technical.

**Technical**: I need to be able to reply/quote existing comments. An example: let's say I am half through the list of the activity responses/comments and I want to quote a comment. I would need a button to reply/quote that comment.

Once I use the quote button -and here I come with the design issue- what will happen?

**Design**: I can think of three alternatives:
1) When I use the quote button the keyboard and the input form **appear** at the bottom of the screen. This means while scrolling everything is hide. In this way you can continue reading afterwards. 
2) When I use the quote button the screen scrolls until to bottom to display the keyboard and the input form.
3) Assuming the that input form (only the input) is always visible, if I use the quote button the keyboard appears. In this way you can also continue where you were reading before. 

I am between 1 and 3. What do you think?

**Comment by rafaelklaessen** [comment]
I think 1 is the best

**Comment by rafaelklaessen** [comment]
I'm going to create a different issue for the design of it
