### ISSUE TITLE
Comment form send button only sends after the keyboard's gone

### ISSUE THREAD

**Issue by rafaelklaessen** [WELTEN/dojo-ibl-mobile#16]

**Comment by rafaelklaessen** [comment]
The TouchableHighlight only triggers when there's no keyboard up, apparently.

**Comment by rafaelklaessen** [comment]
We can use the blur event on the textinput: http://stackoverflow.com/questions/30810679/touchablehighlight-wont-accept-press-events-while-keyboard-is-open

**Comment by Titogelo** [comment]
Sounds like a fair solution. Go for it.

**Comment by rafaelklaessen** [comment]
Turned out to be something else: http://stackoverflow.com/questions/35543753/react-native-textinput-blur-consumes-touchablehighlight-press-event
