### ISSUE TITLE
When a quoted comment is deleted, the reply should show "Comment deleted"

### ISSUE THREAD

**Issue by rafaelklaessen** [WELTEN/dojo-ibl-mobile#18]
Rather than just showing nothing at all. This makes it more clear for users what's going on.

**Comment by Titogelo** [comment]
I need to include this in the browser version then

**Comment by rafaelklaessen** [comment]
The browser version shows a 'blank' comment (no profile pic, username or content)

**Comment by rafaelklaessen** [comment]
Like a - as username.
