### ISSUE TITLE
Improve user communication

### ISSUE THREAD

**Issue by rafaelklaessen** [WELTEN/dojo-ibl-mobile#20]
For example, add a popup when there's no internet connection and show an activity indicator in the lazy load of comments (see #10).

**Comment by Titogelo** [comment]
I would name this issue Improve users' interface feedback. We aim at explaining -with little hints and popups- what is happening in the platform so that we can provide a pleasant experience to the users.

**Comment by rafaelklaessen** [comment]
Hm yeah, I named the issue like this because it's the communication towards the user; it isn't necessarily feedback to an action.
