### ISSUE TITLE
Implement the showing of runs/phases/activities/comments

### ISSUE THREAD

**Issue by rafaelklaessen** [WELTEN/dojo-ibl-mobile#22]

**Comment by Titogelo** [comment]
Regarding the list of runs it is difficult to identify from which inquiries those runs are. In my case I have a quite large list of runs. Maybe adding the title of the inquiry (game) to the title of the run would help.

Something like: "game title" - "run title"

**Comment by rafaelklaessen** [comment]
What about putting the inquiry title after the run title, but a bit greyed out?

**Comment by Titogelo** [comment]
perfect!
