### ISSUE TITLE
Store all server requested data in localstorage so that the app works offline as well

### ISSUE THREAD

**Issue by rafaelklaessen** [WELTEN/dojo-ibl-mobile#9]

**Comment by rafaelklaessen** [comment]
The idea of this is that the app stores server fetched data on the device. When the user opens the app again, the local storage items (if they are there) will be showed first. After that, if there is an internet connection, requests will be made to the server to update the locally stored data.

**Comment by Titogelo** [comment]
Some considerations: 

to update the data stored locally you can use the server time to retrieve only the new data on the server from a point in time given.
